version: '3'
services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - dockerphp
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: phpdocker
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - dockerphp
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    ports:
      - "8080:80"
    networks:
      - dockerphp
networks:
  dockerphp:
